import 'dart:ui';

List<Map<String, dynamic>> offersModels = [
  {
    'image': 'assets/images/image 4.png',
    'title': 'Salade aux amend...',
    'place': 'La fontaine',
    'price': '4.00 £',
    'isCoupon': true,
    'isReduction': false,
    'reductionPercentage': '20 %',
    'reductionPrice': '20.00 £',
    'isCoins': false,
    'coins': '',
    'quantite': '',
    'date': '15 Mars 2023',
    'distance': '1 km',
    'color': Color(0xff9699E9),
  },
  {
    'image': 'assets/images/image 88.png',
    'title': 'Plat agneau avec ...',
    'place': 'La fontaine',
    'price': '40.00 £',
    'isCoupon': false,
    'isReduction': false,
    'reductionPercentage': '20 %',
    'reductionPrice': '20.00 £',
    'isCoins': true,
    'coins': '10 Coins',
    'quantite': '20 disponibles',
    'date': '15 Mars 2023',
    'distance': '1 km',
    'color': Color(0xff9699E9),
  },
  {
    'image': 'assets/images/image 4.png',
    'title': 'Plat agneau avec ...',
    'place': 'Burger King',
    'price': '12.00 £',
    'isCoupon': false,
    'isReduction': true,
    'reductionPercentage': '35 %',
    'reductionPrice': '20.00 £',
    'isCoins': false,
    'coins': '',
    'quantite': '20 disponibles',
    'date': '15 Mars 2023',
    'distance': '1 km',
    'color': Color(0xff9699E9),
  },
];

List<Map<String, dynamic>> shopsModels = [
  {
    'image': 'assets/images/image 3.png',
    'name': 'Food Planet',
    'dollar': true,
    'check': true,
    'like': true,
    'distance': '860m',
    'place': 'Monaco ',
    'peoples': '2.5K',
    'rating': '4.5',
    'antiGasp': false,
    'livraison': false,
  },
  {
    'image': 'assets/images/restaurant2.png',
    'name': 'Beach Club resto',
    'dollar': true,
    'check': true,
    'like': true,
    'distance': '5km',
    'place': 'Cannes',
    'peoples': '2.5K',
    'rating': '4.5',
    'antiGasp': true,
    'livraison': true,
  },
  {
    'image': 'assets/images/marinearesto.png',
    'name': 'Le Marin',
    'dollar': true,
    'check': true,
    'like': false,
    'distance': '20km',
    'place': 'Toulon',
    'peoples': '2.1K',
    'rating': '4.5',
    'antiGasp': true,
    'livraison': true,
  },
];
